### ISSUE TITLE
We need to refactor the Metadata API

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/metadata-api#25]
Potential tasks:

- [ ] Get rid of Flask and use a more modern framework (@r-marquez)
- [ ] Deprecate the mongodb driver and bring elasticsearch logic to metadata-api core project
- [ ] Enable elasticsearch queries into the metadata api
- [ ] #26 
- [ ] #27 
- [x] https://github.com/nevermined-io/docs/issues/37
